### ISSUE TITLE
テストを書く

### ISSUE THREAD

**Issue by arsley** [czc-dev/Ordering-system#1]
modelとintegrationテストを書いておきたい。

**Comment by assly** [comment]
96094184a9e4ff2199a9c3f6aa77107e47c98fa1
modelのテストを書きました。

**Comment by assly** [comment]
7206def7ed4a58273d194b5384805d690aae1c1f
controllerの基本的なテスト (`index` の部分) を書き上げました。

**Comment by assly** [comment]
6a083e1152b94a299beeb8a2231b9996aea7249d
`Employee`のテスト

**Comment by assly** [comment]
今後はステータスコードのテストは重視しなくていい。
- APIサーバーとかと違って見た目(View)の方が正しければ良い =  そこまで重要じゃない

**Comment by arsley** [comment]
#20 
全体的にテストの質を向上させました。

**Comment by arsley** [comment]
capybaraを使ったUIとかのテストもそろそろ書きたいところ...
